### ISSUE TITLE
Swift cannot create container and list contents

### ISSUE THREAD

**Issue by taiojia** [nofdev/fastforward#5]
When i create container from horizon, I got the error:

```
Can not create container
```

I found the log of swift are:

```
object-reconstructor: Exception dumping recon cache: #012Traceback (most recent call last):#012  File "/usr/lib/python2.7/dist-packages/swift/common/utils.py", line 2801, in dump_recon_cache#012    with lock_file(cache_file, lock_timeout, unlink=False) as cf:#012  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__#012    return self.gen.next()#012  File "/usr/lib/python2.7/dist-packages/swift/common/utils.py", line 2047, in lock_file#012    fd = os.open(filename, flags)#012OSError: [Errno 13] Permission denied: '/var/cache/swift/object.recon'
```

**Comment by taiojia** [comment]
This may a bug of playback 0.3.8 when install swift-proxy not on controller node.
otherwise, we need ensure the correct permission of swift-proxy:

```
sudo mkdir -p /var/cache/swift
sudo chown -R root:swift /var/cache/swift
sudo chmod -R 775 /var/cache/swift
sudo swift-init all reload
```

**Comment by pootow** [comment]
😱swift was always stable in previous versions and I even skipped all the
cases of swift for this version!
2016年7月28日 11:34，"Taio Jia" notifications@github.com写道：

**Comment by taiojia** [comment]
Fixed in next version.
